name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Current image version for given MLflow Exporter and Ubuntu versions"
        default: "1.0"
        type: string
        required: false
    secrets:
      DOCKER_HUB_CHARMED_USERNAME:
        required: true
      DOCKER_HUB_CHARMED_ACCESS_TOKEN:
        required: true
  workflow_call:
    inputs:
      version:
        description: "Current image version for given MLflow Exporter and Ubuntu versions"
        default: "1.0"
        type: string
        required: false
    secrets:
      DOCKER_HUB_CHARMED_USERNAME:
        required: true
      DOCKER_HUB_CHARMED_ACCESS_TOKEN:
        required: true

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    permissions:
      id-token: write
      contents: write
      security-events: write
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          docker build -t ${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:${{ github.sha }} .
      
      - name: Run image tests
        run: |
          docker run --rm -it -p 8000:8000 -d ${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:${{ github.sha }}
          sleep 5
          curl -I --fail localhost:8000

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_CHARMED_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_CHARMED_ACCESS_TOKEN }}
      
      - name: Docker push image to DockerHub
        run: |
          docker tag ${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:${{ github.sha }} ${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:${{ inputs.version }}-22.04
          docker push ${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:${{ inputs.version }}-22.04
